// <auto-generated Note="Disabling CodeMaid sorting />
using System.Text.Json.Serialization;

namespace VsLinuxDebugger.Core.Remote
{
  public class Configuration
  {
    public string Name { get; set; } = "Debug on Linux";


    public string Type { get; set; } = "coreclr";

    /// <summary>Request action (i.e. 'launch', 'attach'</summary>
    public string Request { get; set; } = "launch";

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string Program { get; set; }   //// _remoteDotNetPath;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string[] Args { get; set; }    //// => _args;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string Cwd { get; set; }       //// => _remoteDebugFolder;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool StopAtEntry { get; set; } //// => _stopAtEntry;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string Console => "internalConsole";

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string Env { get; set; }       //// => _environmentVariables;

    //// ---- TESTING PHASE BELOW ----

    /// <summary>Program name to debug (i.e. 'TestApp.exe').</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string ProcessName { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public PipeTransport PipeTransport { get; set; }
  }
}
