using System.Collections.Generic;

// <auto-generated Note="Disabling CodeMaid sorting />
namespace VsLinuxDebugger.Core.Remote
{
  public class Launch
  {
    private string _remoteDotNetPath;
    private string[] _args;
    private string _remoteOutputFolder;
    private Dictionary<string, string> _environmentVariables;
    private bool _stopAtEntry;

    /// <summary>Launch JSON class</summary>
    /// <param name="dotNetPath">Remote machine DotNet path</param>
    /// <param name="remoteAppFileName">Name of app(.dll) or full path on remote machine.</param>
    /// <param name="remoteOutputFolder">Working directory (CWD) where app resides.</param>
    /// <param name="envVariables">Custom environment variables.</param>
    public Launch(string dotNetPath, string remoteAppFileName, string remoteOutputFolder, Dictionary<string, string> envVariables = default, bool stopAtEntry = false)
      : this(dotNetPath, new[] { remoteAppFileName }, remoteOutputFolder, envVariables, stopAtEntry)
    {
    }

    /// <summary>Launch JSON class</summary>
    /// <param name="program">Executable to launch on the remote machine (i.e. `dotnet`, or the app itself for a self-contained deployment).</param>
    /// <param name="args">Arguments passed to <paramref name="program"/> (i.e. the assembly path for a framework-dependent deployment).</param>
    /// <param name="remoteOutputFolder">Working directory (CWD) where app resides.</param>
    /// <param name="envVariables">Custom environment variables.</param>
    public Launch(string program, string[] args, string remoteOutputFolder, Dictionary<string, string> envVariables = default, bool stopAtEntry = false)
    {
      _remoteDotNetPath = program;
      _args = args;
      _remoteOutputFolder = remoteOutputFolder;
      _environmentVariables = envVariables;
      _stopAtEntry = stopAtEntry;

      Configurations = new List<Configuration>
      {
        new Configuration
        {
          Program = _remoteDotNetPath,
          Args = _args,
          Cwd = _remoteOutputFolder,
          StopAtEntry = _stopAtEntry,
          Env = _environmentVariables,
        }
      };
    }

    /// <summary>Creates a launch.json that attaches to an already-running remote process,
    /// instead of launching a new one. Use this for a debuggee managed by something else
    /// (i.e. a systemd service), so the debugger attaches to that exact process rather than
    /// starting a second, unmanaged instance alongside it.</summary>
    /// <param name="processId">Remote process ID to attach to.</param>
    public static Launch CreateAttach(int processId)
    {
      var launch = new Launch(program: null, args: null, remoteOutputFolder: null);
      launch.Configurations[0].Request = "attach";
      launch.Configurations[0].ProcessId = processId;
      return launch;
    }

    public string Version => "0.2.0";

    public string Adapter { get; set; }

    public string AdapterArgs { get; set; }

    public List<Configuration> Configurations { get; set; }
  }
}
