using System.Text.Json.Serialization;

// <auto-generated Note="Disabling CodeMaid sorting />
namespace VsLinuxDebugger.Core.Remote
{
  public class PipeTransport
  {
    /// <summary>Pipe command (i.e. '${workspaceFolder}').</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string PipeCmd { get; set; }

    /// <summary>Pipe program (i.e. 'wsl.exe')</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string PipeProgram { get; set; }

    //// [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    //// public List<string> PipeArgs { get; set; }

    /// <summary>Path to VSDBG.exe (i.e. 'wine64 ~/vs-debugger/vsdbg.exe')</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string DebuggerPath { get; set; }
  }
}
