// <auto-generated Note="Disabling CodeMaid sorting />
namespace VsLinuxDebugger.Core
{
  public class LaunchJsonConfig
  {
    public LaunchJsonConfig(string program, string[] progArgs, string workingDirecotry)
    {
      Cwd = workingDirecotry;
    }

    public string Name { get; set; } = ".NET Core Launch";

    public string Type { get; set; } = "coreclr";

    public string Program { get; set; } = "dotnet";

    public string[] args { get; set; }

    public string Cwd { get; set; }

    public string Request { get; set; } = "launch";

    public bool StopAtEntry { get; set; }
  }
}
